Overlapping signatures
======================

Here, we want to find out to what extent BioQC signatures overlap 
and if we can correct for that statistically. 

```{r}
library(RColorBrewer)
library(BioQC)
library(ggplot2)
library(reshape2)
gmtFile = system.file("extdata/exp.tissuemark.affy.roche.symbols.gmt", package="BioQC")
gmt <- readGmt(gmtFile)
```

Compute jaccard index for each pair of signatures
```{r}
sigs = names(gmt)
jaccard.mat = matrix(ncol=length(sigs), nrow=length(sigs))
rownames(jaccard.mat) = sigs
colnames(jaccard.mat) = sigs
for (i in 1:length(sigs)) {
  for (j in 1:length(sigs)) {
    set1 = gmt[[i]]$genes
    set2 = gmt[[j]]$genes
    jaccard.mat[i, j] = length(intersect(set1, set2)) / length(union(set1, set2))
  }
}

```

Plot the matrix
```{r}
mat.molten = melt(jaccard.mat)
ggplot(data=mat.molten, aes(x=Var2, y=Var1, fill=value)) + geom_tile() +
        coord_equal() +
        scale_fill_gradientn(colours = hm.palette(100)) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Store the pairwise intersection in a matrix. 
```{r}
intersection.list = lapply(gmt, function(sig1) {
  return (lapply(gmt, function(sig2) {
    set1 = sig1$genes
    set2 = sig2$genes
    return (intersect(set1, set2))
  }))
})
save(intersection.list, file="data/signature_intersection.Rdata")
```

