name: conda

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for setuptools-scm

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          mamba install -y pip bioconductor-edger bioconductor-bioqc
          pip install .[tests]
        shell: bash

      - name: Test with nosetest
        run: |
          nosetests --with-doctest -e "_extended"
          
        shell: bash
