# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {R: "4.1", Python: 3.7, os: ubuntu-latest}
          - {R: "4.1", Python: 3.8, os: ubuntu-latest}
          - {R: "4.1", Python: 3.9, os: ubuntu-latest}
          - {R: "4.1", Python: 3.7, os: macos-latest}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.config.Python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.Python }}
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.R }}
      - name: Install R packages
        shell: Rscript {0}
        run: |
          install.packages('BiocManager', repos='https://cloud.r-project.org')
          BiocManager::install(c("BioQC", "edgeR"))
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[tests]
      - name: Check formatting
        run: |
          black --check .
      - name: Test with nosetest
        run: |
          nosetests --with-doctest -e "_extended"
